import { deckNames } from '../decks';
import { userIds } from '../users';
import { SeedCard } from './cards';
import { cardsDefaultValues } from './cardsDefaultValues';

export const citiesCards: SeedCard = [
	{
		japanese: '都市計画',
		hiragana: 'としけいかく',
		japaneseSynonyms: [],
		english: 'urban planning',
		englishSynonyms: [],
		hint: 'city planning',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '交通',
		hiragana: 'こうつう',
		japaneseSynonyms: [],
		english: 'transportation',
		englishSynonyms: [],
		hint: 'traffic',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '道路',
		hiragana: 'どうろ',
		japaneseSynonyms: [],
		english: 'road',
		englishSynonyms: [],
		hint: 'road path',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '公共交通機関',
		hiragana: 'こうきょうこうつうきかん',
		japaneseSynonyms: [],
		english: 'public transportation',
		englishSynonyms: [],
		hint: 'public transport system',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '地下鉄',
		hiragana: 'ちかてつ',
		japaneseSynonyms: [],
		english: 'subway',
		englishSynonyms: [],
		hint: 'underground iron',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: 'バス停',
		hiragana: 'ばすてい',
		japaneseSynonyms: [],
		english: 'bus stop',
		englishSynonyms: [],
		hint: 'bus stop',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '信号',
		hiragana: 'しんごう',
		japaneseSynonyms: [],
		english: 'traffic light',
		englishSynonyms: [],
		hint: 'signal',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '歩道',
		hiragana: 'ほどう',
		japaneseSynonyms: [],
		english: 'sidewalk',
		englishSynonyms: [],
		hint: 'walk path',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '交差点',
		hiragana: 'こうさてん',
		japaneseSynonyms: [],
		english: 'intersection',
		englishSynonyms: [],
		hint: 'cross point',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '橋',
		hiragana: 'はし',
		japaneseSynonyms: [],
		english: 'bridge',
		englishSynonyms: [],
		hint: 'bridge',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '公園',
		hiragana: 'こうえん',
		japaneseSynonyms: [],
		english: 'park',
		englishSynonyms: [],
		hint: 'public garden',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '広場',
		hiragana: 'ひろば',
		japaneseSynonyms: [],
		english: 'square',
		englishSynonyms: [],
		hint: 'open place',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '図書館',
		hiragana: 'としょかん',
		japaneseSynonyms: [],
		english: 'library',
		englishSynonyms: [],
		hint: 'book building',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '病院',
		hiragana: 'びょういん',
		japaneseSynonyms: [],
		english: 'hospital',
		englishSynonyms: [],
		hint: 'sick institution',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '消防署',
		hiragana: 'しょうぼうしょ',
		japaneseSynonyms: [],
		english: 'fire station',
		englishSynonyms: [],
		hint: 'firefighting office',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '警察署',
		hiragana: 'けいさつしょ',
		japaneseSynonyms: [],
		english: 'police station',
		englishSynonyms: [],
		hint: 'police office',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '郵便局',
		hiragana: 'ゆうびんきょく',
		japaneseSynonyms: [],
		english: 'post office',
		englishSynonyms: [],
		hint: 'mail office',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '学校',
		hiragana: 'がっこう',
		japaneseSynonyms: [],
		english: 'school',
		englishSynonyms: [],
		hint: 'school',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '大学',
		hiragana: 'だいがく',
		japaneseSynonyms: [],
		english: 'university',
		englishSynonyms: [],
		hint: 'big learning',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '商店街',
		hiragana: 'しょうてんがい',
		japaneseSynonyms: [],
		english: 'shopping street',
		englishSynonyms: [],
		hint: 'commerce street',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '市場',
		hiragana: 'いちば',
		japaneseSynonyms: [],
		english: 'market',
		englishSynonyms: [],
		hint: 'marketplace',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '住宅地',
		hiragana: 'じゅうたくち',
		japaneseSynonyms: [],
		english: 'residential area',
		englishSynonyms: [],
		hint: 'housing area',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: 'ビル',
		hiragana: 'びる',
		japaneseSynonyms: [],
		english: 'building',
		englishSynonyms: [],
		hint: 'building',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: 'マンション',
		hiragana: 'まんしょん',
		japaneseSynonyms: [],
		english: 'apartment',
		englishSynonyms: [],
		hint: 'mansion',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '駐車場',
		hiragana: 'ちゅうしゃじょう',
		japaneseSynonyms: [],
		english: 'parking lot',
		englishSynonyms: [],
		hint: 'parking place',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '地下道',
		hiragana: 'ちかどう',
		japaneseSynonyms: [],
		english: 'underground passage',
		englishSynonyms: [],
		hint: 'underground path',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '高速道路',
		hiragana: 'こうそくどうろ',
		japaneseSynonyms: [],
		english: 'highway',
		englishSynonyms: [],
		hint: 'high speed road',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '交番',
		hiragana: 'こうばん',
		japaneseSynonyms: [],
		english: 'police box',
		englishSynonyms: [],
		hint: 'police box',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '信号機',
		hiragana: 'しんごうき',
		japaneseSynonyms: [],
		english: 'traffic signal',
		englishSynonyms: [],
		hint: 'signal machine',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '横断歩道',
		hiragana: 'おうだんほどう',
		japaneseSynonyms: [],
		english: 'crosswalk',
		englishSynonyms: [],
		hint: 'crossing walk path',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '地下街',
		hiragana: 'ちかがい',
		japaneseSynonyms: [],
		english: 'underground mall',
		englishSynonyms: [],
		hint: 'underground town',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '歩行者天国',
		hiragana: 'ほこうしゃてんごく',
		japaneseSynonyms: [],
		english: 'pedestrian zone',
		englishSynonyms: [],
		hint: 'pedestrian heaven',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '市役所',
		hiragana: 'しやくしょ',
		japaneseSynonyms: [],
		english: 'city hall',
		englishSynonyms: [],
		hint: 'city office',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '区役所',
		hiragana: 'くやくしょ',
		japaneseSynonyms: [],
		english: 'ward office',
		englishSynonyms: [],
		hint: 'ward office',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '町内会',
		hiragana: 'ちょうないかい',
		japaneseSynonyms: [],
		english: 'neighborhood association',
		englishSynonyms: [],
		hint: 'town inside meeting',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: 'ゴミ収集',
		hiragana: 'ごみしゅうしゅう',
		japaneseSynonyms: [],
		english: 'garbage collection',
		englishSynonyms: [],
		hint: 'garbage collection',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '水道',
		hiragana: 'すいどう',
		japaneseSynonyms: [],
		english: 'water supply',
		englishSynonyms: [],
		hint: 'water way',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '電気',
		hiragana: 'でんき',
		japaneseSynonyms: [],
		english: 'electricity',
		englishSynonyms: [],
		hint: 'electricity',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: 'ガス',
		hiragana: 'がす',
		japaneseSynonyms: [],
		english: 'gas',
		englishSynonyms: [],
		hint: 'gas',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '下水道',
		hiragana: 'げすいどう',
		japaneseSynonyms: [],
		english: 'sewerage',
		englishSynonyms: [],
		hint: 'sewer way',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '公衆トイレ',
		hiragana: 'こうしゅうといれ',
		japaneseSynonyms: [],
		english: 'public toilet',
		englishSynonyms: [],
		hint: 'public toilet',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '街灯',
		hiragana: 'がいとう',
		japaneseSynonyms: [],
		english: 'streetlight',
		englishSynonyms: [],
		hint: 'street light',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '歩道橋',
		hiragana: 'ほどうきょう',
		japaneseSynonyms: [],
		english: 'pedestrian bridge',
		englishSynonyms: [],
		hint: 'walk path bridge',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '地下駐車場',
		hiragana: 'ちかちゅうしゃじょう',
		japaneseSynonyms: [],
		english: 'underground parking lot',
		englishSynonyms: [],
		hint: 'underground parking place',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '高層ビル',
		hiragana: 'こうそうびる',
		japaneseSynonyms: [],
		english: 'skyscraper',
		englishSynonyms: [],
		hint: 'high rise building',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '住宅街',
		hiragana: 'じゅうたくがい',
		japaneseSynonyms: [],
		english: 'residential area',
		englishSynonyms: [],
		hint: 'housing street',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '商業地区',
		hiragana: 'しょうぎょうちく',
		japaneseSynonyms: [],
		english: 'commercial district',
		englishSynonyms: [],
		hint: 'commerce area',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '工業地区',
		hiragana: 'こうぎょうちく',
		japaneseSynonyms: [],
		english: 'industrial district',
		englishSynonyms: [],
		hint: 'industry area',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '観光地',
		hiragana: 'かんこうち',
		japaneseSynonyms: [],
		english: 'tourist spot',
		englishSynonyms: [],
		hint: 'sightseeing place',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '観光案内所',
		hiragana: 'かんこうあんないじょ',
		japaneseSynonyms: [],
		english: 'tourist information center',
		englishSynonyms: [],
		hint: 'sightseeing guide place',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '市民センター',
		hiragana: 'しみんせんたー',
		japaneseSynonyms: [],
		english: 'community center',
		englishSynonyms: [],
		hint: 'citizen center',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '文化会館',
		hiragana: 'ぶんかかいかん',
		japaneseSynonyms: [],
		english: 'cultural center',
		englishSynonyms: [],
		hint: 'culture meeting hall',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '市立図書館',
		hiragana: 'しりつとしょかん',
		japaneseSynonyms: [],
		english: 'municipal library',
		englishSynonyms: [],
		hint: 'city library',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '市立美術館',
		hiragana: 'しりつびじゅつかん',
		japaneseSynonyms: [],
		english: 'municipal art museum',
		englishSynonyms: [],
		hint: 'city art museum',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '市立博物館',
		hiragana: 'しりつはくぶつかん',
		japaneseSynonyms: [],
		english: 'municipal museum',
		englishSynonyms: [],
		hint: 'city museum',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '市立動物園',
		hiragana: 'しりつどうぶつえん',
		japaneseSynonyms: [],
		english: 'municipal zoo',
		englishSynonyms: [],
		hint: 'city zoo',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
	{
		japanese: '市立植物園',
		hiragana: 'しりつしょくぶつえん',
		japaneseSynonyms: [],
		english: 'municipal botanical garden',
		englishSynonyms: [],
		hint: 'city botanical garden',
		userId: userIds[0],
		deckName: deckNames.cities,
		...cardsDefaultValues,
	},
];
