import { deckNames } from '../decks';
import { userIds } from '../users';
import { SeedCard } from './cards';
import { cardsDefaultValues } from './cardsDefaultValues';

export const harryPotterCards: SeedCard = [
	{
		japanese: '杖',
		hiragana: 'つえ',
		japaneseSynonyms: [],
		english: 'wand',
		englishSynonyms: [],
		hint: 'wand',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: 'フクロウ',
		hiragana: 'ふくろう',
		japaneseSynonyms: [],
		english: 'owl',
		englishSynonyms: [],
		hint: 'owl',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '呪文',
		hiragana: 'じゅもん',
		japaneseSynonyms: [],
		english: 'spell',
		englishSynonyms: [],
		hint: 'spell',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔法',
		hiragana: 'まほう',
		japaneseSynonyms: [],
		english: 'magic',
		englishSynonyms: [],
		hint: 'magic',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔法使い',
		hiragana: 'まほうつかい',
		japaneseSynonyms: [],
		english: 'wizard',
		englishSynonyms: [],
		hint: 'wizard',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔女',
		hiragana: 'まじょ',
		japaneseSynonyms: [],
		english: 'witch',
		englishSynonyms: [],
		hint: 'witch',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: 'ホグワーツ',
		hiragana: 'ほぐわーつ',
		japaneseSynonyms: [],
		english: 'Hogwarts',
		englishSynonyms: [],
		hint: 'Hogwarts',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: 'クィディッチ',
		hiragana: 'くぃでぃっち',
		japaneseSynonyms: [],
		english: 'Quidditch',
		englishSynonyms: [],
		hint: 'Quidditch',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔法薬',
		hiragana: 'まほうやく',
		japaneseSynonyms: [],
		english: 'potion',
		englishSynonyms: [],
		hint: 'potion',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '闇の魔術',
		hiragana: 'やみのまじゅつ',
		japaneseSynonyms: [],
		english: 'dark arts',
		englishSynonyms: [],
		hint: 'dark arts',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '箒',
		hiragana: 'ほうき',
		japaneseSynonyms: [],
		english: 'broom',
		englishSynonyms: [],
		hint: 'broom',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: 'ドラゴン',
		hiragana: 'どらごん',
		japaneseSynonyms: [],
		english: 'dragon',
		englishSynonyms: [],
		hint: 'dragon',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔法省',
		hiragana: 'まほうしょう',
		japaneseSynonyms: [],
		english: 'Ministry of Magic',
		englishSynonyms: [],
		hint: 'Ministry of Magic',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '不死鳥',
		hiragana: 'ふしちょう',
		japaneseSynonyms: [],
		english: 'phoenix',
		englishSynonyms: [],
		hint: 'phoenix',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '透明マント',
		hiragana: 'とうめいまんと',
		japaneseSynonyms: [],
		english: 'invisibility cloak',
		englishSynonyms: [],
		hint: 'invisibility cloak',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔法の杖',
		hiragana: 'まほうのつえ',
		japaneseSynonyms: [],
		english: 'magic wand',
		englishSynonyms: [],
		hint: 'magic wand',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔法の本',
		hiragana: 'まほうのほん',
		japaneseSynonyms: [],
		english: 'spellbook',
		englishSynonyms: [],
		hint: 'spellbook',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔法の鏡',
		hiragana: 'まほうのかがみ',
		japaneseSynonyms: [],
		english: 'magic mirror',
		englishSynonyms: [],
		hint: 'magic mirror',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔法の石',
		hiragana: 'まほうのいし',
		japaneseSynonyms: [],
		english: "philosopher's stone",
		englishSynonyms: [],
		hint: "philosopher's stone",
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
	{
		japanese: '魔法の帽子',
		hiragana: 'まほうのぼうし',
		japaneseSynonyms: [],
		english: 'sorting hat',
		englishSynonyms: [],
		hint: 'sorting hat',
		userId: userIds[0],
		deckName: deckNames.harryPotter,
		...cardsDefaultValues,
	},
];
