import { deckNames } from '../decks';
import { userIds } from '../users';
import { SeedCard } from './cards';
import { cardsDefaultValues } from './cardsDefaultValues';

export const musicCards: SeedCard = [
	{
		japanese: '三連符',
		hiragana: 'さんれんぷ',
		japaneseSynonyms: [],
		english: 'triplet',
		englishSynonyms: [],
		hint: 'three connected token (三: three, 連: connected, 符: token)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '二連符',
		hiragana: 'にれんぷ',
		japaneseSynonyms: [],
		english: 'duple',
		englishSynonyms: [],
		hint: 'two serial token (二: two, 連: serial, 符: token)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '伴奏',
		hiragana: 'ばんそう',
		japaneseSynonyms: [],
		english: 'accompaniment',
		englishSynonyms: [],
		hint: 'accompaniment (伴: accompany, 奏: play)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '全休符',
		hiragana: 'ぜんきゅうふ',
		japaneseSynonyms: [],
		english: 'whole rest',
		englishSynonyms: [],
		hint: 'whole rest token (全: whole, 休: rest, 符: token)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '全音符',
		hiragana: 'ぜんおんぷ',
		japaneseSynonyms: [],
		english: 'whole note',
		englishSynonyms: [],
		hint: 'whole sound token (全: whole, 音: sound, 符: token)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},

	{
		japanese: '指揮者',
		hiragana: 'しきしゃ',
		japaneseSynonyms: [],
		english: 'conductor',
		englishSynonyms: [],
		hint: 'leader of the orchestra (指: point, 揮: command, 者: person)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'オーケストラ',
		hiragana: 'おーけすとら',
		japaneseSynonyms: [],
		english: 'orchestra',
		englishSynonyms: [],
		hint: 'large instrumental ensemble (オーケストラ: orchestra)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},

	{
		japanese: '音階',
		hiragana: 'おんかい',
		japaneseSynonyms: [],
		english: 'scale',
		englishSynonyms: [],
		hint: 'sequence of musical notes (音: sound, 階: steps)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '和音',
		hiragana: 'わおん',
		japaneseSynonyms: [],
		english: 'chord',
		englishSynonyms: [],
		hint: 'combination of notes (和: harmony, 音: sound)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '旋律',
		hiragana: 'せんりつ',
		japaneseSynonyms: [],
		english: 'melody',
		englishSynonyms: [],
		hint: 'sequence of musical notes (旋: melody, 律: rhythm)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'リズム',
		hiragana: 'りずむ',
		japaneseSynonyms: [],
		english: 'rhythm',
		englishSynonyms: [],
		hint: 'pattern of sounds (リズム: rhythm)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'テンポ',
		hiragana: 'てんぽ',
		japaneseSynonyms: [],
		english: 'tempo',
		englishSynonyms: [],
		hint: 'speed of music (テンポ: tempo)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '強弱',
		hiragana: 'きょうじゃく',
		japaneseSynonyms: [],
		english: 'dynamics',
		englishSynonyms: [],
		hint: 'volume of music (強: strong, 弱: weak)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '拍子',
		hiragana: 'ひょうし',
		japaneseSynonyms: [],
		english: 'time signature',
		englishSynonyms: [],
		hint: 'musical meter (拍: beat, 子: sign)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '音符',
		hiragana: 'おんぷ',
		japaneseSynonyms: [],
		english: 'note',
		englishSynonyms: [],
		hint: 'musical symbol (音: sound, 符: token)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '休符',
		hiragana: 'きゅうふ',
		japaneseSynonyms: [],
		english: 'rest',
		englishSynonyms: [],
		hint: 'silence in music (休: rest, 符: token)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '音程',
		hiragana: 'おんてい',
		japaneseSynonyms: [],
		english: 'interval',
		englishSynonyms: [],
		hint: 'distance between notes (音: sound, 程: degree)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '調',
		hiragana: 'ちょう',
		japaneseSynonyms: [],
		english: 'key',
		englishSynonyms: [],
		hint: 'tonal center (調: key)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '調和',
		hiragana: 'ちょうわ',
		japaneseSynonyms: [],
		english: 'harmony',
		englishSynonyms: [],
		hint: 'combination of notes (調: harmony, 和: peace)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '楽器',
		hiragana: 'がっき',
		japaneseSynonyms: [],
		english: 'instrument',
		englishSynonyms: [],
		hint: 'musical device (楽: music, 器: instrument)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'ピアノ',
		hiragana: 'ぴあの',
		japaneseSynonyms: [],
		english: 'piano',
		englishSynonyms: [],
		hint: 'keyboard instrument (ピアノ: piano)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'ヴァイオリン',
		hiragana: 'ヴぁいおりん',
		japaneseSynonyms: [],
		english: 'violin',
		englishSynonyms: [],
		hint: 'string instrument (ヴァイオリン: violin)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'チェロ',
		hiragana: 'ちぇろ',
		japaneseSynonyms: [],
		english: 'cello',
		englishSynonyms: [],
		hint: 'string instrument (チェロ: cello)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'コントラバス',
		hiragana: 'こんとらばす',
		japaneseSynonyms: [],
		english: 'double bass',
		englishSynonyms: ['contrabass'],
		hint: 'string instrument (コントラバス: double bass)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'フルート',
		hiragana: 'ふるーと',
		japaneseSynonyms: [],
		english: 'flute',
		englishSynonyms: [],
		hint: 'woodwind instrument (フルート: flute)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'クラリネット',
		hiragana: 'くらりねっと',
		japaneseSynonyms: [],
		english: 'clarinet',
		englishSynonyms: [],
		hint: 'woodwind instrument (クラリネット: clarinet)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'オーボエ',
		hiragana: 'おーぼえ',
		japaneseSynonyms: [],
		english: 'oboe',
		englishSynonyms: [],
		hint: 'woodwind instrument (オーボエ: oboe)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'ファゴット',
		hiragana: 'ふぁごっと',
		japaneseSynonyms: [],
		english: 'bassoon',
		englishSynonyms: [],
		hint: 'woodwind instrument (ファゴット: bassoon)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'サクソフォン',
		hiragana: 'さくそふぉん',
		japaneseSynonyms: [],
		english: 'saxophone',
		englishSynonyms: [],
		hint: 'woodwind instrument (サクソフォン: saxophone)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'トランペット',
		hiragana: 'とらんぺっと',
		japaneseSynonyms: [],
		english: 'trumpet',
		englishSynonyms: [],
		hint: 'brass instrument (トランペット: trumpet)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'トロンボーン',
		hiragana: 'とろんぼーん',
		japaneseSynonyms: [],
		english: 'trombone',
		englishSynonyms: [],
		hint: 'brass instrument (トロンボーン: trombone)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'ホルン',
		hiragana: 'ほるん',
		japaneseSynonyms: [],
		english: 'horn',
		englishSynonyms: ['French horn'],
		hint: 'brass instrument (ホルン: horn)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'チューバ',
		hiragana: 'ちゅーば',
		japaneseSynonyms: [],
		english: 'tuba',
		englishSynonyms: [],
		hint: 'brass instrument (チューバ: tuba)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '打楽器',
		hiragana: 'だがっき',
		japaneseSynonyms: [],
		english: 'percussion',
		englishSynonyms: [],
		hint: 'percussion instrument (打: hit, 楽: music, 器: instrument)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'ティンパニ',
		hiragana: 'てぃんぱに',
		japaneseSynonyms: [],
		english: 'timpani',
		englishSynonyms: ['kettledrums'],
		hint: 'percussion instrument (ティンパニ: timpani)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'シンバル',
		hiragana: 'しんばる',
		japaneseSynonyms: [],
		english: 'cymbals',
		englishSynonyms: [],
		hint: 'percussion instrument (シンバル: cymbals)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'トライアングル',
		hiragana: 'とらいあんぐる',
		japaneseSynonyms: [],
		english: 'triangle',
		englishSynonyms: [],
		hint: 'percussion instrument (トライアングル: triangle)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'バスドラム',
		hiragana: 'ばすどらむ',
		japaneseSynonyms: [],
		english: 'bass drum',
		englishSynonyms: [],
		hint: 'percussion instrument (バスドラム: bass drum)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'スネアドラム',
		hiragana: 'すねあどらむ',
		japaneseSynonyms: [],
		english: 'snare drum',
		englishSynonyms: [],
		hint: 'percussion instrument (スネアドラム: snare drum)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '木琴',
		hiragana: 'もっきん',
		japaneseSynonyms: [],
		english: 'xylophone',
		englishSynonyms: [],
		hint: 'percussion instrument (木: wood, 琴: zither)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'マリンバ',
		hiragana: 'まりんば',
		japaneseSynonyms: [],
		english: 'marimba',
		englishSynonyms: [],
		hint: 'percussion instrument (マリンバ: marimba)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'グロッケンシュピール',
		hiragana: 'ぐろっけんしゅぴーる',
		japaneseSynonyms: [],
		english: 'glockenspiel',
		englishSynonyms: [],
		hint: 'percussion instrument (グロッケンシュピール: glockenspiel)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: 'ハープ',
		hiragana: 'はーぷ',
		japaneseSynonyms: [],
		english: 'harp',
		englishSynonyms: [],
		hint: 'string instrument (ハープ: harp)',
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
	{
		japanese: '指揮棒',
		hiragana: 'しきぼう',
		japaneseSynonyms: [],
		english: 'baton',
		englishSynonyms: [],
		hint: "conductor's tool (指: point, 揮: command, 棒: stick)",
		userId: userIds[0],
		deckName: deckNames.music,
		...cardsDefaultValues,
	},
];
