import { deckNames } from '../decks';
import { userIds } from '../users';
import { SeedCard } from './cards';
import { cardsDefaultValues } from './cardsDefaultValues';

export const politicsCards: SeedCard = [
	{
		japanese: '選挙',
		hiragana: 'せんきょ',
		japaneseSynonyms: [],
		english: 'election',
		englishSynonyms: [],
		hint: 'select and raise',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会',
		hiragana: 'ぎかい',
		japaneseSynonyms: [],
		english: 'congress',
		englishSynonyms: [],
		hint: 'deliberate meeting',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '大統領',
		hiragana: 'だいとうりょう',
		japaneseSynonyms: [],
		english: 'president',
		englishSynonyms: [],
		hint: 'big unify leader',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政策',
		hiragana: 'せいさく',
		japaneseSynonyms: [],
		english: 'policy',
		englishSynonyms: [],
		hint: 'political measure',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '共和党',
		hiragana: 'きょうわとう',
		japaneseSynonyms: [],
		english: 'Republican Party',
		englishSynonyms: [],
		hint: 'cooperate harmony party',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '民主党',
		hiragana: 'みんしゅとう',
		japaneseSynonyms: [],
		english: 'Democratic Party',
		englishSynonyms: [],
		hint: 'people master party',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議員',
		hiragana: 'ぎいん',
		japaneseSynonyms: [],
		english: 'member of parliament',
		englishSynonyms: [],
		hint: 'deliberate member',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '投票所',
		hiragana: 'とうひょうじょ',
		japaneseSynonyms: [],
		english: 'polling station',
		englishSynonyms: [],
		hint: 'throw ballot place',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '憲法',
		hiragana: 'けんぽう',
		japaneseSynonyms: [],
		english: 'constitution',
		englishSynonyms: [],
		hint: 'law of the land',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '外交',
		hiragana: 'がいこう',
		japaneseSynonyms: [],
		english: 'diplomacy',
		englishSynonyms: [],
		hint: 'outside exchange',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '内政',
		hiragana: 'ないせい',
		japaneseSynonyms: [],
		english: 'domestic policy',
		englishSynonyms: [],
		hint: 'inside politics',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '国会',
		hiragana: 'こっかい',
		japaneseSynonyms: [],
		english: 'national assembly',
		englishSynonyms: [],
		hint: 'country meeting',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '首相',
		hiragana: 'しゅしょう',
		japaneseSynonyms: [],
		english: 'prime minister',
		englishSynonyms: [],
		hint: 'head minister',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議案',
		hiragana: 'ぎあん',
		japaneseSynonyms: [],
		english: 'bill',
		englishSynonyms: [],
		hint: 'deliberate proposal',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政党',
		hiragana: 'せいとう',
		japaneseSynonyms: [],
		english: 'political party',
		englishSynonyms: [],
		hint: 'politics party',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '選挙権',
		hiragana: 'せんきょけん',
		japaneseSynonyms: [],
		english: 'suffrage',
		englishSynonyms: [],
		hint: 'election right',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議長',
		hiragana: 'ぎちょう',
		japaneseSynonyms: [],
		english: 'chairperson',
		englishSynonyms: [],
		hint: 'deliberate leader',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '法案',
		hiragana: 'ほうあん',
		japaneseSynonyms: [],
		english: 'legislative bill',
		englishSynonyms: [],
		hint: 'law proposal',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会制民主主義',
		hiragana: 'ぎかいせいみんしゅしゅぎ',
		japaneseSynonyms: [],
		english: 'parliamentary democracy',
		englishSynonyms: [],
		hint: 'deliberate system people master principle',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '内閣',
		hiragana: 'ないかく',
		japaneseSynonyms: [],
		english: 'cabinet',
		englishSynonyms: [],
		hint: 'inside chamber',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '大臣',
		hiragana: 'だいじん',
		japaneseSynonyms: [],
		english: 'minister',
		englishSynonyms: [],
		hint: 'big official',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政権',
		hiragana: 'せいけん',
		japaneseSynonyms: [],
		english: 'administration',
		englishSynonyms: [],
		hint: 'politics authority',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '国際関係',
		hiragana: 'こくさいかんけい',
		japaneseSynonyms: [],
		english: 'international relations',
		englishSynonyms: [],
		hint: 'country between relation',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '条約',
		hiragana: 'じょうやく',
		japaneseSynonyms: [],
		english: 'treaty',
		englishSynonyms: [],
		hint: 'article promise',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議論',
		hiragana: 'ぎろん',
		japaneseSynonyms: [],
		english: 'debate',
		englishSynonyms: [],
		hint: 'deliberate discussion',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '投票率',
		hiragana: 'とうひょうりつ',
		japaneseSynonyms: [],
		english: 'voter turnout',
		englishSynonyms: [],
		hint: 'throw ballot rate',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '選挙運動',
		hiragana: 'せんきょうんどう',
		japaneseSynonyms: [],
		english: 'election campaign',
		englishSynonyms: [],
		hint: 'election movement',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政界',
		hiragana: 'せいかい',
		japaneseSynonyms: [],
		english: 'political world',
		englishSynonyms: [],
		hint: 'politics world',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議席',
		hiragana: 'ぎせき',
		japaneseSynonyms: [],
		english: 'parliamentary seat',
		englishSynonyms: [],
		hint: 'deliberate seat',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政局',
		hiragana: 'せいきょく',
		japaneseSynonyms: [],
		english: 'political situation',
		englishSynonyms: [],
		hint: 'politics situation',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '選挙区',
		hiragana: 'せんきょく',
		japaneseSynonyms: [],
		english: 'electoral district',
		englishSynonyms: [],
		hint: 'election district',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政令',
		hiragana: 'せいれい',
		japaneseSynonyms: [],
		english: 'government ordinance',
		englishSynonyms: [],
		hint: 'politics command',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会運営',
		hiragana: 'ぎかいうんえい',
		japaneseSynonyms: [],
		english: 'parliamentary management',
		englishSynonyms: [],
		hint: 'deliberate meeting operation',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政務',
		hiragana: 'せいむ',
		japaneseSynonyms: [],
		english: 'political affairs',
		englishSynonyms: [],
		hint: 'politics duty',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '外交政策',
		hiragana: 'がいこうせいさく',
		japaneseSynonyms: [],
		english: 'foreign policy',
		englishSynonyms: [],
		hint: 'outside exchange political measure',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '国際連合',
		hiragana: 'こくさいれんごう',
		japaneseSynonyms: [],
		english: 'United Nations',
		englishSynonyms: [],
		hint: 'country between union',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会改革',
		hiragana: 'ぎかいかいかく',
		japaneseSynonyms: [],
		english: 'parliamentary reform',
		englishSynonyms: [],
		hint: 'deliberate meeting reform',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政権交代',
		hiragana: 'せいけんこうたい',
		japaneseSynonyms: [],
		english: 'change of government',
		englishSynonyms: [],
		hint: 'politics authority change',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会選挙',
		hiragana: 'ぎかいせんきょ',
		japaneseSynonyms: [],
		english: 'parliamentary election',
		englishSynonyms: [],
		hint: 'deliberate meeting election',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政党政治',
		hiragana: 'せいとうせいじ',
		japaneseSynonyms: [],
		english: 'party politics',
		englishSynonyms: [],
		hint: 'politics party politics',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会制度',
		hiragana: 'ぎかいせいど',
		japaneseSynonyms: [],
		english: 'parliamentary system',
		englishSynonyms: [],
		hint: 'deliberate meeting system',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政党内閣',
		hiragana: 'せいとうないかく',
		japaneseSynonyms: [],
		english: 'party cabinet',
		englishSynonyms: [],
		hint: 'politics party inside chamber',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会民主主義',
		hiragana: 'ぎかいみんしゅしゅぎ',
		japaneseSynonyms: [],
		english: 'parliamentary democracy',
		englishSynonyms: [],
		hint: 'deliberate meeting people master principle',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政党連立',
		hiragana: 'せいとうれんりつ',
		japaneseSynonyms: [],
		english: 'party coalition',
		englishSynonyms: [],
		hint: 'politics party coalition',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会運営委員会',
		hiragana: 'ぎかいうんえいいいんかい',
		japaneseSynonyms: [],
		english: 'parliamentary steering committee',
		englishSynonyms: [],
		hint: 'deliberate meeting operation committee',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政党助成金',
		hiragana: 'せいとうじょせいきん',
		japaneseSynonyms: [],
		english: 'party subsidy',
		englishSynonyms: [],
		hint: 'politics party assistance money',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会運営法',
		hiragana: 'ぎかいうんえいほう',
		japaneseSynonyms: [],
		english: 'parliamentary management law',
		englishSynonyms: [],
		hint: 'deliberate meeting operation law',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政党助成制度',
		hiragana: 'せいとうじょせいせいど',
		japaneseSynonyms: [],
		english: 'party subsidy system',
		englishSynonyms: [],
		hint: 'politics party assistance system',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会運営委員長',
		hiragana: 'ぎかいうんえいいいんちょう',
		japaneseSynonyms: [],
		english: 'parliamentary steering committee chairman',
		englishSynonyms: [],
		hint: 'deliberate meeting operation committee leader',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政党助成法',
		hiragana: 'せいとうじょせいほう',
		japaneseSynonyms: [],
		english: 'party subsidy law',
		englishSynonyms: [],
		hint: 'politics party assistance law',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会運営委員会法',
		hiragana: 'ぎかいうんえいいいんかいほう',
		japaneseSynonyms: [],
		english: 'parliamentary steering committee law',
		englishSynonyms: [],
		hint: 'deliberate meeting operation committee law',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政党助成制度法',
		hiragana: 'せいとうじょせいせいどほう',
		japaneseSynonyms: [],
		english: 'party subsidy system law',
		englishSynonyms: [],
		hint: 'politics party assistance system law',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '議会運営委員会制度',
		hiragana: 'ぎかいうんえいいいんかいせいど',
		japaneseSynonyms: [],
		english: 'parliamentary steering committee system',
		englishSynonyms: [],
		hint: 'deliberate meeting operation committee system',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
	{
		japanese: '政党助成制度法案',
		hiragana: 'せいとうじょせいせいどほうあん',
		japaneseSynonyms: [],
		english: 'party subsidy system bill',
		englishSynonyms: [],
		hint: 'politics party assistance system bill',
		userId: userIds[0],
		deckName: deckNames.politics,
		...cardsDefaultValues,
	},
];
