import { deckNames } from '../decks';
import { userIds } from '../users';
import { SeedCard } from './cards';
import { cardsDefaultValues } from './cardsDefaultValues';

export const techBusinessCards: SeedCard = [
	{
		japanese: '会議',
		hiragana: 'かいぎ',
		japaneseSynonyms: [],
		english: 'meeting',
		englishSynonyms: [],
		hint: 'gathering discussion',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '議題',
		hiragana: 'ぎだい',
		japaneseSynonyms: [],
		english: 'agenda',
		englishSynonyms: [],
		hint: 'discussion topic',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '報告',
		hiragana: 'ほうこく',
		japaneseSynonyms: [],
		english: 'report',
		englishSynonyms: [],
		hint: 'inform announce',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '提案',
		hiragana: 'ていあん',
		japaneseSynonyms: [],
		english: 'proposal',
		englishSynonyms: [],
		hint: 'suggest plan',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '決定',
		hiragana: 'けってい',
		japaneseSynonyms: [],
		english: 'decision',
		englishSynonyms: [],
		hint: 'decide determine',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '議事録',
		hiragana: 'ぎじろく',
		japaneseSynonyms: [],
		english: 'meeting minutes',
		englishSynonyms: [],
		hint: 'meeting write record',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '進捗',
		hiragana: 'しんちょく',
		japaneseSynonyms: [],
		english: 'progress',
		englishSynonyms: [],
		hint: 'advance progress',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '目標',
		hiragana: 'もくひょう',
		japaneseSynonyms: [],
		english: 'goal',
		englishSynonyms: [],
		hint: 'target aim',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '戦略',
		hiragana: 'せんりゃく',
		japaneseSynonyms: [],
		english: 'strategy',
		englishSynonyms: [],
		hint: 'war plan',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '計画',
		hiragana: 'けいかく',
		japaneseSynonyms: [],
		english: 'plan',
		englishSynonyms: [],
		hint: 'plot scheme',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '予算',
		hiragana: 'よさん',
		japaneseSynonyms: [],
		english: 'budget',
		englishSynonyms: [],
		hint: 'estimate calculate',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '収益',
		hiragana: 'しゅうえき',
		japaneseSynonyms: [],
		english: 'revenue',
		englishSynonyms: [],
		hint: 'income profit',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '費用',
		hiragana: 'ひよう',
		japaneseSynonyms: [],
		english: 'cost',
		englishSynonyms: [],
		hint: 'expense use',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '利益',
		hiragana: 'りえき',
		japaneseSynonyms: [],
		english: 'profit',
		englishSynonyms: [],
		hint: 'gain benefit',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '損失',
		hiragana: 'そんしつ',
		japaneseSynonyms: [],
		english: 'loss',
		englishSynonyms: [],
		hint: 'damage lose',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '契約',
		hiragana: 'けいやく',
		japaneseSynonyms: [],
		english: 'contract',
		englishSynonyms: [],
		hint: 'pledge promise',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '顧客',
		hiragana: 'こきゃく',
		japaneseSynonyms: [],
		english: 'customer',
		englishSynonyms: [],
		hint: 'client guest',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '市場',
		hiragana: 'しじょう',
		japaneseSynonyms: [],
		english: 'market',
		englishSynonyms: [],
		hint: 'marketplace',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '競争',
		hiragana: 'きょうそう',
		japaneseSynonyms: [],
		english: 'competition',
		englishSynonyms: [],
		hint: 'compete contend',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '分析',
		hiragana: 'ぶんせき',
		japaneseSynonyms: [],
		english: 'analysis',
		englishSynonyms: [],
		hint: 'divide analyze',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '調査',
		hiragana: 'ちょうさ',
		japaneseSynonyms: [],
		english: 'survey',
		englishSynonyms: [],
		hint: 'investigate examine',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '開発',
		hiragana: 'かいはつ',
		japaneseSynonyms: [],
		english: 'development',
		englishSynonyms: [],
		hint: 'open develop',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '設計',
		hiragana: 'せっけい',
		japaneseSynonyms: [],
		english: 'design',
		englishSynonyms: [],
		hint: 'plan design',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '実装',
		hiragana: 'じっそう',
		japaneseSynonyms: [],
		english: 'implementation',
		englishSynonyms: [],
		hint: 'realize install',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'テスト',
		hiragana: 'てすと',
		japaneseSynonyms: [],
		english: 'test',
		englishSynonyms: [],
		hint: 'test',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'リリース',
		hiragana: 'りりーす',
		japaneseSynonyms: [],
		english: 'release',
		englishSynonyms: [],
		hint: 'release',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'バグ',
		hiragana: 'ばぐ',
		japaneseSynonyms: [],
		english: 'bug',
		englishSynonyms: [],
		hint: 'bug',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: '修正',
		hiragana: 'しゅうせい',
		japaneseSynonyms: [],
		english: 'fix',
		englishSynonyms: [],
		hint: 'correct revise',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'デプロイ',
		hiragana: 'でぷろい',
		japaneseSynonyms: [],
		english: 'deploy',
		englishSynonyms: [],
		hint: 'deploy',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'サーバー',
		hiragana: 'さーばー',
		japaneseSynonyms: [],
		english: 'server',
		englishSynonyms: [],
		hint: 'server',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'クラウド',
		hiragana: 'くらうど',
		japaneseSynonyms: [],
		english: 'cloud',
		englishSynonyms: [],
		hint: 'cloud',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'データベース',
		hiragana: 'でーたべーす',
		japaneseSynonyms: [],
		english: 'database',
		englishSynonyms: [],
		hint: 'database',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'インフラ',
		hiragana: 'いんふら',
		japaneseSynonyms: [],
		english: 'infrastructure',
		englishSynonyms: [],
		hint: 'infrastructure',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'セキュリティ',
		hiragana: 'せきゅりてぃ',
		japaneseSynonyms: [],
		english: 'security',
		englishSynonyms: [],
		hint: 'security',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'バックアップ',
		hiragana: 'ばっくあっぷ',
		japaneseSynonyms: [],
		english: 'backup',
		englishSynonyms: [],
		hint: 'backup',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'ロードバランサー',
		hiragana: 'ろーどばらんさー',
		japaneseSynonyms: [],
		english: 'load balancer',
		englishSynonyms: [],
		hint: 'load balancer',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'スケーラビリティ',
		hiragana: 'すけーらびりてぃ',
		japaneseSynonyms: [],
		english: 'scalability',
		englishSynonyms: [],
		hint: 'scalability',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'パフォーマンス',
		hiragana: 'ぱふぉーまんす',
		japaneseSynonyms: [],
		english: 'performance',
		englishSynonyms: [],
		hint: 'performance',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'ユーザー',
		hiragana: 'ゆーざー',
		japaneseSynonyms: [],
		english: 'user',
		englishSynonyms: [],
		hint: 'user',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'インターフェース',
		hiragana: 'いんたーふぇーす',
		japaneseSynonyms: [],
		english: 'interface',
		englishSynonyms: [],
		hint: 'interface',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'ユーザーエクスペリエンス',
		hiragana: 'ゆーざーえくすぺりえんす',
		japaneseSynonyms: [],
		english: 'user experience',
		englishSynonyms: [],
		hint: 'user experience',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'ユーザビリティ',
		hiragana: 'ゆーざびりてぃ',
		japaneseSynonyms: [],
		english: 'usability',
		englishSynonyms: [],
		hint: 'usability',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'フィードバック',
		hiragana: 'ふぃーどばっく',
		japaneseSynonyms: [],
		english: 'feedback',
		englishSynonyms: [],
		hint: 'feedback',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'プロジェクト',
		hiragana: 'ぷろじぇくと',
		japaneseSynonyms: [],
		english: 'project',
		englishSynonyms: [],
		hint: 'project',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'タスク',
		hiragana: 'たすく',
		japaneseSynonyms: [],
		english: 'task',
		englishSynonyms: [],
		hint: 'task',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'スプリント',
		hiragana: 'すぷりんと',
		japaneseSynonyms: [],
		english: 'sprint',
		englishSynonyms: [],
		hint: 'sprint',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'アジャイル',
		hiragana: 'あじゃいる',
		japaneseSynonyms: [],
		english: 'agile',
		englishSynonyms: [],
		hint: 'agile',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'スクラム',
		hiragana: 'すくらむ',
		japaneseSynonyms: [],
		english: 'scrum',
		englishSynonyms: [],
		hint: 'scrum',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'カンバン',
		hiragana: 'かんばん',
		japaneseSynonyms: [],
		english: 'kanban',
		englishSynonyms: [],
		hint: 'kanban',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'デイリースタンドアップ',
		hiragana: 'でいりーすたんどあっぷ',
		japaneseSynonyms: [],
		english: 'daily stand-up',
		englishSynonyms: [],
		hint: 'daily stand-up',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'レトロスペクティブ',
		hiragana: 'れとろすぺくてぃぶ',
		japaneseSynonyms: [],
		english: 'retrospective',
		englishSynonyms: [],
		hint: 'retrospective',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'プロダクトオーナー',
		hiragana: 'ぷろだくとおーなー',
		japaneseSynonyms: [],
		english: 'product owner',
		englishSynonyms: [],
		hint: 'product owner',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'スクラムマスター',
		hiragana: 'すくらむますたー',
		japaneseSynonyms: [],
		english: 'scrum master',
		englishSynonyms: [],
		hint: 'scrum master',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'バックログ',
		hiragana: 'ばっくろぐ',
		japaneseSynonyms: [],
		english: 'backlog',
		englishSynonyms: [],
		hint: 'backlog',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'ユーザーストーリー',
		hiragana: 'ゆーざーすとーりー',
		japaneseSynonyms: [],
		english: 'user story',
		englishSynonyms: [],
		hint: 'user story',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
	{
		japanese: 'エピック',
		hiragana: 'えぴっく',
		japaneseSynonyms: [],
		english: 'epic',
		englishSynonyms: [],
		hint: 'epic',
		userId: userIds[0],
		deckName: deckNames.techBusiness,
		...cardsDefaultValues,
	},
];
