import { deckNames } from '../decks';
import { userIds } from '../users';
import { SeedCard } from './cards';
import { cardsDefaultValues } from './cardsDefaultValues';

export const travelCards: SeedCard = [
	{
		japanese: '空港',
		hiragana: 'くうこう',
		japaneseSynonyms: [],
		english: 'airport',
		englishSynonyms: [],
		hint: 'air harbor (空: air, 港: harbor)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '飛行機',
		hiragana: 'ひこうき',
		japaneseSynonyms: [],
		english: 'airplane',
		englishSynonyms: [],
		hint: 'flying machine (飛: fly, 行: go, 機: machine)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '電車',
		hiragana: 'でんしゃ',
		japaneseSynonyms: [],
		english: 'train',
		englishSynonyms: [],
		hint: 'electric vehicle (電: electric, 車: vehicle)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '駅',
		hiragana: 'えき',
		japaneseSynonyms: [],
		english: 'station',
		englishSynonyms: [],
		hint: 'station',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: 'バス',
		hiragana: 'ばす',
		japaneseSynonyms: [],
		english: 'bus',
		englishSynonyms: [],
		hint: 'bus',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: 'タクシー',
		hiragana: 'たくしー',
		japaneseSynonyms: [],
		english: 'taxi',
		englishSynonyms: [],
		hint: 'taxi',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: 'ホテル',
		hiragana: 'ほてる',
		japaneseSynonyms: [],
		english: 'hotel',
		englishSynonyms: [],
		hint: 'hotel',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '予約',
		hiragana: 'よやく',
		japaneseSynonyms: [],
		english: 'reservation',
		englishSynonyms: [],
		hint: 'reservation (予: beforehand, 約: promise)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光',
		hiragana: 'かんこう',
		japaneseSynonyms: [],
		english: 'sightseeing',
		englishSynonyms: [],
		hint: 'sightseeing (観: view, 光: light)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '地図',
		hiragana: 'ちず',
		japaneseSynonyms: [],
		english: 'map',
		englishSynonyms: [],
		hint: 'map (地: earth, 図: diagram)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: 'ガイド',
		hiragana: 'がいど',
		japaneseSynonyms: [],
		english: 'guide',
		englishSynonyms: [],
		hint: 'guide',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '旅行',
		hiragana: 'りょこう',
		japaneseSynonyms: [],
		english: 'travel',
		englishSynonyms: [],
		hint: 'travel (旅: journey, 行: go)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '荷物',
		hiragana: 'にもつ',
		japaneseSynonyms: [],
		english: 'luggage',
		englishSynonyms: [],
		hint: 'luggage (荷: load, 物: thing)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: 'パスポート',
		hiragana: 'ぱすぽーと',
		japaneseSynonyms: [],
		english: 'passport',
		englishSynonyms: [],
		hint: 'passport',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '出発',
		hiragana: 'しゅっぱつ',
		japaneseSynonyms: [],
		english: 'departure',
		englishSynonyms: [],
		hint: 'departure (出: exit, 発: departure)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '到着',
		hiragana: 'とうちゃく',
		japaneseSynonyms: [],
		english: 'arrival',
		englishSynonyms: [],
		hint: 'arrival (到: arrive, 着: wear)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光地',
		hiragana: 'かんこうち',
		japaneseSynonyms: [],
		english: 'tourist spot',
		englishSynonyms: [],
		hint: 'tourist spot (観: view, 光: light, 地: place)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光案内所',
		hiragana: 'かんこうあんないじょ',
		japaneseSynonyms: [],
		english: 'tourist information center',
		englishSynonyms: [],
		hint: 'tourist information center (観: view, 光: light, 案内: guide, 所: place)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '市内観光',
		hiragana: 'しないかんこう',
		japaneseSynonyms: [],
		english: 'city tour',
		englishSynonyms: [],
		hint: 'city tour (市: city, 内: inside, 観光: sightseeing)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '海外旅行',
		hiragana: 'かいがいりょこう',
		japaneseSynonyms: [],
		english: 'overseas travel',
		englishSynonyms: [],
		hint: 'overseas travel (海: sea, 外: outside, 旅行: travel)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '国内旅行',
		hiragana: 'こくないりょこう',
		japaneseSynonyms: [],
		english: 'domestic travel',
		englishSynonyms: [],
		hint: 'domestic travel (国: country, 内: inside, 旅行: travel)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '旅行代理店',
		hiragana: 'りょこうだいりてん',
		japaneseSynonyms: [],
		english: 'travel agency',
		englishSynonyms: [],
		hint: 'travel agency (旅行: travel, 代理: agency, 店: shop)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光バス',
		hiragana: 'かんこうばす',
		japaneseSynonyms: [],
		english: 'tour bus',
		englishSynonyms: [],
		hint: 'tour bus (観光: sightseeing, バス: bus)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光客',
		hiragana: 'かんこうきゃく',
		japaneseSynonyms: [],
		english: 'tourist',
		englishSynonyms: [],
		hint: 'tourist (観光: sightseeing, 客: guest)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '旅行者',
		hiragana: 'りょこうしゃ',
		japaneseSynonyms: [],
		english: 'traveler',
		englishSynonyms: [],
		hint: 'traveler (旅行: travel, 者: person)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光名所',
		hiragana: 'かんこうめいしょ',
		japaneseSynonyms: [],
		english: 'tourist attraction',
		englishSynonyms: [],
		hint: 'tourist attraction (観光: sightseeing, 名所: famous place)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光地図',
		hiragana: 'かんこうちず',
		japaneseSynonyms: [],
		english: 'tourist map',
		englishSynonyms: [],
		hint: 'tourist map (観光: sightseeing, 地図: map)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光案内',
		hiragana: 'かんこうあんない',
		japaneseSynonyms: [],
		english: 'tourist guide',
		englishSynonyms: [],
		hint: 'tourist guide (観光: sightseeing, 案内: guide)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光バスツアー',
		hiragana: 'かんこうばすつあー',
		japaneseSynonyms: [],
		english: 'sightseeing bus tour',
		englishSynonyms: [],
		hint: 'sightseeing bus tour (観光: sightseeing, バス: bus, ツアー: tour)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光ガイド',
		hiragana: 'かんこうがいど',
		japaneseSynonyms: [],
		english: 'tour guide',
		englishSynonyms: [],
		hint: 'tour guide (観光: sightseeing, ガイド: guide)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光案内所',
		hiragana: 'かんこうあんないじょ',
		japaneseSynonyms: [],
		english: 'tourist information center',
		englishSynonyms: [],
		hint: 'tourist information center (観光: sightseeing, 案内: guide, 所: place)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光地図',
		hiragana: 'かんこうちず',
		japaneseSynonyms: [],
		english: 'tourist map',
		englishSynonyms: [],
		hint: 'tourist map (観光: sightseeing, 地図: map)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光名所',
		hiragana: 'かんこうめいしょ',
		japaneseSynonyms: [],
		english: 'tourist attraction',
		englishSynonyms: [],
		hint: 'tourist attraction (観光: sightseeing, 名所: famous place)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光案内',
		hiragana: 'かんこうあんない',
		japaneseSynonyms: [],
		english: 'tourist guide',
		englishSynonyms: [],
		hint: 'tourist guide (観光: sightseeing, 案内: guide)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光バスツアー',
		hiragana: 'かんこうばすつあー',
		japaneseSynonyms: [],
		english: 'sightseeing bus tour',
		englishSynonyms: [],
		hint: 'sightseeing bus tour (観光: sightseeing, バス: bus, ツアー: tour)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光ガイド',
		hiragana: 'かんこうがいど',
		japaneseSynonyms: [],
		english: 'tour guide',
		englishSynonyms: [],
		hint: 'tour guide (観光: sightseeing, ガイド: guide)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光案内所',
		hiragana: 'かんこうあんないじょ',
		japaneseSynonyms: [],
		english: 'tourist information center',
		englishSynonyms: [],
		hint: 'tourist information center (観光: sightseeing, 案内: guide, 所: place)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光地図',
		hiragana: 'かんこうちず',
		japaneseSynonyms: [],
		english: 'tourist map',
		englishSynonyms: [],
		hint: 'tourist map (観光: sightseeing, 地図: map)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光名所',
		hiragana: 'かんこうめいしょ',
		japaneseSynonyms: [],
		english: 'tourist attraction',
		englishSynonyms: [],
		hint: 'tourist attraction (観光: sightseeing, 名所: famous place)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光案内',
		hiragana: 'かんこうあんない',
		japaneseSynonyms: [],
		english: 'tourist guide',
		englishSynonyms: [],
		hint: 'tourist guide (観光: sightseeing, 案内: guide)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光バスツアー',
		hiragana: 'かんこうばすつあー',
		japaneseSynonyms: [],
		english: 'sightseeing bus tour',
		englishSynonyms: [],
		hint: 'sightseeing bus tour (観光: sightseeing, バス: bus, ツアー: tour)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光ガイド',
		hiragana: 'かんこうがいど',
		japaneseSynonyms: [],
		english: 'tour guide',
		englishSynonyms: [],
		hint: 'tour guide (観光: sightseeing, ガイド: guide)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光案内所',
		hiragana: 'かんこうあんないじょ',
		japaneseSynonyms: [],
		english: 'tourist information center',
		englishSynonyms: [],
		hint: 'tourist information center (観光: sightseeing, 案内: guide, 所: place)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光地図',
		hiragana: 'かんこうちず',
		japaneseSynonyms: [],
		english: 'tourist map',
		englishSynonyms: [],
		hint: 'tourist map (観光: sightseeing, 地図: map)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光名所',
		hiragana: 'かんこうめいしょ',
		japaneseSynonyms: [],
		english: 'tourist attraction',
		englishSynonyms: [],
		hint: 'tourist attraction (観光: sightseeing, 名所: famous place)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光案内',
		hiragana: 'かんこうあんない',
		japaneseSynonyms: [],
		english: 'tourist guide',
		englishSynonyms: [],
		hint: 'tourist guide (観光: sightseeing, 案内: guide)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
	{
		japanese: '観光バスツアー',
		hiragana: 'かんこうばすつあー',
		japaneseSynonyms: [],
		english: 'sightseeing bus tour',
		englishSynonyms: [],
		hint: 'sightseeing bus tour (観光: sightseeing, バス: bus, ツアー: tour)',
		userId: userIds[0],
		deckName: deckNames.travel,
		...cardsDefaultValues,
	},
];
