import { Card } from "@prisma/client";
import { deckSeedIds } from "./decks";
import { userIds } from "./users";

const defaultValues = { srsLevel: 0, nextStudy: new Date() };

export const cards: Omit<Card, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 1,
    japanese: '三連符',
    japaneseSynonyms: [],
    english: 'triplet',
    englishSynonyms: [],
    hint: 'three connected token',
    userId: userIds[0],
    deckId: deckSeedIds['Japanese Music Vocabulary'],
    ...defaultValues,
  },
  {
    id: 2,
    japanese: '二連符',
    japaneseSynonyms: [],
    english: 'duple',
    englishSynonyms: ['duplet'],
    hint: 'two connected token',
    userId: userIds[0],
    deckId: deckSeedIds['Japanese Music Vocabulary'],
    ...defaultValues,
  },
  {
    id: 3,
    japanese: '伴奏',
    japaneseSynonyms: [],
    english: 'accompaniment',
    englishSynonyms: [],
    hint: 'two connected token',
    userId: userIds[0],
    deckId: deckSeedIds['Japanese Music Vocabulary'],
    ...defaultValues,
  },
  {
    id: 4,
    japanese: '弦楽器',
    japaneseSynonyms: [],
    english: 'stringed instrument',
    englishSynonyms: ['string instrument'],
    hint: 'string instrument',
    userId: userIds[0],
    deckId: deckSeedIds['Japanese Music Vocabulary'],
    ...defaultValues,
  },
  {
    id: 5,
    japanese: '全休符',
    japaneseSynonyms: [],
    english: 'whole rest',
    englishSynonyms: [],
    hint: 'whole rest token',
    userId: userIds[0],
    deckId: deckSeedIds['Japanese Music Vocabulary'],
    ...defaultValues,
  },
  {
    id: 6,
    japanese: '全音符',
    japaneseSynonyms: [],
    english: 'whole note',
    englishSynonyms: [],
    hint: 'whole sound token',
    userId: userIds[0],
    deckId: deckSeedIds['Japanese Music Vocabulary'],
    ...defaultValues,
  },
  {
    id: 7,
    japanese: '八分音符',
    japaneseSynonyms: [],
    english: 'eighth note',
    englishSynonyms: ['8th note'],
    hint: '8 part sound token',
    userId: userIds[0],
    deckId: deckSeedIds['Japanese Music Vocabulary'],
    ...defaultValues,
  },
];