import { reverseObject } from "@/utils/data";
import { Language } from "@prisma/client";

export const languageSeedIds: Record<string, number> = {
    English: 0,
    Japanese: 1,
    'Chinese (Mandarin)': 3,
};

export const reverseLanguageSeedIds: Record<number, string> = reverseObject(languageSeedIds);

export const languages: Omit<Language, 'id' | 'createdAt' | 'updatedAt'>[] = [
    { name: 'Afrikaans', identifier: 'afrikaans' },
    { name: 'Albanian', identifier: 'albanian' },
    { name: 'Arabic', identifier: 'arabic' },
    { name: 'Armenian', identifier: 'armenian' },
    { name: 'Basque', identifier: 'basque' },
    { name: 'Bengali', identifier: 'bengali' },
    { name: 'Bulgarian', identifier: 'bulgarian' },
    { name: 'Catalan', identifier: 'catalan' },
    { name: 'Cambodian', identifier: 'cambodian' },
    { name: 'Chinese (Mandarin)', identifier: 'chineseMandarin' },
    { name: 'Chinese (Cantonese)', identifier: 'chineseCantonese' },
    { name: 'Croatian', identifier: 'croatian' },
    { name: 'Czech', identifier: 'czech' },
    { name: 'Danish', identifier: 'danish' },
    { name: 'Dutch', identifier: 'dutch' },
    { name: 'English', identifier: 'english' },
    { name: 'Estonian', identifier: 'estonian' },
    { name: 'Fiji', identifier: 'fiji' },
    { name: 'Finnish', identifier: 'finnish' },
    { name: 'French', identifier: 'french' },
    { name: 'Georgian', identifier: 'georgian' },
    { name: 'German', identifier: 'german' },
    { name: 'Greek', identifier: 'greek' },
    { name: 'Gujarati', identifier: 'gujarati' },
    { name: 'Hebrew', identifier: 'hebrew' },
    { name: 'Hindi', identifier: 'hindi' },
    { name: 'Hungarian', identifier: 'hungarian' },
    { name: 'Icelandic', identifier: 'icelandic' },
    { name: 'Indonesian', identifier: 'indonesian' },
    { name: 'Irish', identifier: 'irish' },
    { name: 'Italian', identifier: 'italian' },
    { name: 'Japanese', identifier: 'japanese' },
    { name: 'Javanese', identifier: 'javanese' },
    { name: 'Korean', identifier: 'korean' },
    { name: 'Latin', identifier: 'latin' },
    { name: 'Latvian', identifier: 'latvian' },
    { name: 'Lithuanian', identifier: 'lithuanian' },
    { name: 'Macedonian', identifier: 'macedonian' },
    { name: 'Malay', identifier: 'malay' },
    { name: 'Malayalam', identifier: 'malayalam' },
    { name: 'Maltese', identifier: 'maltese' },
    { name: 'Maori', identifier: 'maori' },
    { name: 'Marathi', identifier: 'marathi' },
    { name: 'Mongolian', identifier: 'mongolian' },
    { name: 'Nepali', identifier: 'nepali' },
    { name: 'Norwegian', identifier: 'norwegian' },
    { name: 'Persian', identifier: 'persian' },
    { name: 'Polish', identifier: 'polish' },
    { name: 'Portuguese', identifier: 'portuguese' },
    { name: 'Punjabi', identifier: 'punjabi' },
    { name: 'Quechua', identifier: 'quechua' },
    { name: 'Romanian', identifier: 'romanian' },
    { name: 'Russian', identifier: 'russian' },
    { name: 'Samoan', identifier: 'samoan' },
    { name: 'Serbian', identifier: 'serbian' },
    { name: 'Slovak', identifier: 'slovak' },
    { name: 'Slovenian', identifier: 'slovenian' },
    { name: 'Spanish', identifier: 'spanish' },
    { name: 'Swahili', identifier: 'swahili' },
    { name: 'Swedish', identifier: 'swedish' },
    { name: 'Tamil', identifier: 'tamil' },
    { name: 'Tatar', identifier: 'tatar' },
    { name: 'Telugu', identifier: 'telugu' },
    { name: 'Thai', identifier: 'thai' },
    { name: 'Tibetan', identifier: 'tibetan' },
    { name: 'Tonga', identifier: 'tonga' },
    { name: 'Turkish', identifier: 'turkish' },
    { name: 'Ukrainian', identifier: 'ukrainian' },
    { name: 'Urdu', identifier: 'urdu' },
    { name: 'Uzbek', identifier: 'uzbek' },
    { name: 'Vietnamese', identifier: 'vietnamese' },
    { name: 'Welsh', identifier: 'welsh' },
    { name: 'Xhosa', identifier: 'xhosa' }
];